---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments
sass:
  style: compressed

### content configuration ###
title:       "AfriLeaks Landing Page"
keywords:    "afrileaks, jekyll, open source, github, blog"
description: "AfriLeaks is an online system which enables users to anonymously send material to investigative media organisations of their choice."
source_link: ""
favicon:     ""
touch_icon:  ""
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)



### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#999999'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  textured:  'img/bg.jpg'
