port: 4000
host: 0.0.0.0


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
lsi: false
markdown: kramdown
highlighter: pygments
sass:
  style: compressed

### content configuration ###
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)
